"""
基础设施 - 数据库：MySQL、Redis、Elasticsearch、Milvus 连接与模型。
"""

from src.infra.database.mysql import (
    async_mysql_pool,
    Base,
    AsyncMySQL,
    User,
    UserProfileV2,
    UserPreference,
    Record,
    ActivityRecordV2,
    NutritionRecordV2,
    NutritionItemV2,
    MeasurementRecordV2,
    MeasurementItemV2,
    StatusRecordV2,
    UserGoal,
    GoalCheckpoint,
    Plan,
    PlanVersion,
    PlanGoalLink,
    PlanItem,
    PlanExecution,
    Conversation,
    ChatMessage,
    PendingAction,
)

__all__ = [
    "async_mysql_pool",
    "Base",
    "AsyncMySQL",
    "User",
    "UserProfileV2",
    "UserPreference",
    "Record",
    "ActivityRecordV2",
    "NutritionRecordV2",
    "NutritionItemV2",
    "MeasurementRecordV2",
    "MeasurementItemV2",
    "StatusRecordV2",
    "UserGoal",
    "GoalCheckpoint",
    "Plan",
    "PlanVersion",
    "PlanGoalLink",
    "PlanItem",
    "PlanExecution",
    "Conversation",
    "ChatMessage",
    "PendingAction",
]
